/* Biology Foundations 互動式考題 — 題庫資料（中英雙語版）
 * Bilingual question bank for "Biological Foundations for Bioinformatics".
 * type: "single" | "multi" | "tf"
 * single ans: "A"|"B"|"C"|"D"
 * multi  ans: ["A","C"]
 * tf     ans: "T"|"F"
 */
window.QUIZ_DATA = {
  biofound: {
    label: "Biology Foundations 互動考題",
    label_en: "Biology Foundations Interactive Quiz",
    labels_en: {
      "Block A 生命的基本單位": "Block A: The Units of Life",
      "Block B 中心法則": "Block B: The Central Dogma",
      "Block C 基因組、遺傳與細胞調控": "Block C: Genome, Inheritance & Cell Regulation",
      "Block D 組學與系統": "Block D: Omics & Systems",
      "Ch.1 為什麼生物資訊學需要生物學": "Ch.1 Why Bioinformatics Needs Biology",
      "Ch.2 細胞與胞器": "Ch.2 Cells & Organelles",
      "Ch.3 四大生物大分子": "Ch.3 The Four Biomolecules",
      "Ch.4 DNA、染色質與染色體": "Ch.4 DNA, Chromatin & Chromosomes",
      "Ch.5 DNA 複製與修復": "Ch.5 DNA Replication & Repair",
      "Ch.6 轉錄與 RNA 加工": "Ch.6 Transcription & RNA Processing",
      "Ch.7 轉譯與蛋白質結構": "Ch.7 Translation & Protein Structure",
      "Ch.8 基因表達調控": "Ch.8 Gene Expression Regulation",
      "Ch.9 基因組結構與註解": "Ch.9 Genome Structure & Annotation",
      "Ch.10 突變與遺傳變異": "Ch.10 Mutations & Genetic Variants",
      "Ch.11 遺傳與群體遺傳": "Ch.11 Inheritance & Population Genetics",
      "Ch.12 表觀遺傳": "Ch.12 Epigenetics",
      "Ch.13 細胞週期、分裂與訊號": "Ch.13 Cell Cycle, Division & Signaling",
      "Ch.14 定序技術與基因組學": "Ch.14 Sequencing & Genomics",
      "Ch.15 轉錄體學": "Ch.15 Transcriptomics",
      "Ch.16 蛋白質體與翻譯後修飾": "Ch.16 Proteomics & PTMs",
      "Ch.17 代謝體與脂質體": "Ch.17 Metabolomics & Lipidomics",
      "Ch.18 系統生物學、多組學與臨床": "Ch.18 Systems Biology, Multi-omics & Clinical"
    },
    subjects: {

"Block A 生命的基本單位": {
  "Ch.1 為什麼生物資訊學需要生物學": [
    { type:"single", stem:"bioinformatics 的核心本質是什麼？", stem_en:"The core essence of bioinformatics is?",
      A:"用程式畫圖", A_en:"Drawing plots with code",
      B:"做網站發表生物資料", B_en:"Building websites that display biological data",
      C:"以計算與統計從生物量測中提取有意義的生物學知識", C_en:"Using computation and statistics to extract biological meaning from measurements",
      D:"自動化實驗室機器人", D_en:"Automating lab robots",
      ans:"C", exp:"分析者必須懂生物學才能判斷『有意義』。", exp_en:"The analyst must understand biology to recognize meaningful signal." },
    { type:"single", stem:"下列哪一個檔案是 1-based closed 座標？", stem_en:"Which file uses 1-based closed coordinates?",
      A:"BED", A_en:"BED", B:"BedGraph", B_en:"BedGraph",
      C:"GTF / GFF3 / VCF", C_en:"GTF / GFF3 / VCF",
      D:"narrowPeak", D_en:"narrowPeak",
      ans:"C", exp:"BED / bedGraph 是 0-based half-open；GTF / GFF / VCF 是 1-based closed。", exp_en:"BED and bedGraph use 0-based half-open; GTF, GFF, and VCF use 1-based closed." },
    { type:"single", stem:"想知道「哪些細胞同時帶特定基因型且高度表達該基因」，最直接的技術組合是？", stem_en:"To assess genotype + expression in the same cell, the most direct combination is?",
      A:"bulk WGS + bulk RNA-seq", A_en:"bulk WGS + bulk RNA-seq",
      B:"scDNA + scRNA 多組學（G&T-seq、Tapestri）", B_en:"scDNA + scRNA multi-omics (G&T-seq, Tapestri)",
      C:"質譜蛋白質體", C_en:"MS proteomics",
      D:"ChIP-seq", D_en:"ChIP-seq",
      ans:"B", exp:"scDNA + scRNA 多組學直接同時讀同細胞的基因型與表達。", exp_en:"scDNA + scRNA multi-omics jointly captures genotype and expression in single cells." },
    { type:"single", stem:"以下哪一個格式紀錄『已對齊的 reads（壓縮）』？", stem_en:"Which format stores aligned (compressed) reads?",
      A:"FASTA", A_en:"FASTA",
      B:"BAM / CRAM", B_en:"BAM / CRAM",
      C:"VCF", C_en:"VCF",
      D:"GTF", D_en:"GTF",
      ans:"B", exp:"BAM/CRAM 是 SAM 的二進位/壓縮版本，記錄 read 對齊資訊。", exp_en:"BAM/CRAM are the binary/compressed forms of SAM." },
    { type:"multi", stem:"以下哪些是常見的生物資訊新手錯誤？（多選）", stem_en:"Common rookie mistakes? (Multi)",
      A:"把 mRNA 表達當作蛋白活性", A_en:"Confusing mRNA expression with protein activity",
      B:"忽略樣本來源與保存方式", B_en:"Ignoring sample provenance and storage",
      C:"忽略批次效應", C_en:"Ignoring batch effects",
      D:"把 effect size 一併報告與檢視", D_en:"Reporting and inspecting effect sizes",
      ans:["A","B","C"], exp:"D 是好習慣不是錯誤；其他三項都是常見錯誤。", exp_en:"D is good practice; the others are common pitfalls." },
    { type:"multi", stem:"哪些屬於『量測 epigenome』的技術？（多選）", stem_en:"Which assays measure the epigenome? (Multi)",
      A:"ATAC-seq", A_en:"ATAC-seq",
      B:"WGBS", B_en:"WGBS",
      C:"ChIP-seq", C_en:"ChIP-seq",
      D:"WGS 變異 calling", D_en:"WGS variant calling",
      ans:["A","B","C"], exp:"WGS 變異 calling 屬於 genome 層級。", exp_en:"WGS variant calling targets the genome, not the epigenome." },
    { type:"tf", stem:"polyA 富集 RNA-seq 可以可靠地偵測大多數 circRNA。", stem_en:"PolyA-enriched RNA-seq can reliably detect most circRNAs.",
      ans:"F", exp:"circRNA 多無 polyA tail，polyA 富集會漏。", exp_en:"Most circRNAs lack polyA tails; polyA enrichment misses them." },
    { type:"tf", stem:"理解資料背後的生物學脈絡是判斷『何為有意義訊號』的關鍵。", stem_en:"Biological context is key to identifying meaningful signal.",
      ans:"T", exp:"沒有生物學就無法判斷訊號真偽。", exp_en:"Without biology, real signal is hard to distinguish from noise." },
    { type:"single", stem:"想偵測『某啟動子的活性』，最直接的技術是？", stem_en:"To measure promoter activity directly?",
      A:"DNA methylation array", A_en:"DNA methylation array",
      B:"ATAC-seq / ChIP-seq / PRO-seq", B_en:"ATAC-seq / ChIP-seq / PRO-seq",
      C:"Sanger sequencing", C_en:"Sanger sequencing",
      D:"untargeted metabolomics", D_en:"Untargeted metabolomics",
      ans:"B", exp:"ATAC（可及性）、ChIP（修飾或 TF 結合）、PRO-seq（活躍轉錄）對應啟動子活性。", exp_en:"ATAC, ChIP, and PRO-seq quantify accessibility, marks/TF, and active transcription." },
    { type:"single", stem:"關於蛋白活性，下列何者最正確？", stem_en:"About protein activity, which is most correct?",
      A:"RNA-seq 即可推論蛋白活性", A_en:"RNA-seq alone tells protein activity",
      B:"蛋白活性受 PTM、定位、結合伴侶共同決定，需 proteomics 與結構資料", B_en:"Protein activity depends on PTMs, localization, partners — needs proteomics/structure",
      C:"蛋白質一旦合成就不可逆", C_en:"Proteins are irreversibly active once made",
      D:"蛋白與 mRNA 量永遠相等", D_en:"Protein and mRNA abundances always match",
      ans:"B", exp:"轉錄 ≠ 翻譯 ≠ 活性，需多組學整合。", exp_en:"Transcription ≠ translation ≠ activity — multi-omics integration is needed." }
  ],
  "Ch.2 細胞與胞器": [
    { type:"single", stem:"心肌細胞 scRNA-seq 中 %mt 自然偏高，原因是？", stem_en:"Why cardiomyocytes show naturally high %mt?",
      A:"細胞普遍死亡", A_en:"Cells are dying",
      B:"高耗能、粒線體含量天然多", B_en:"High energy demand, naturally abundant mitochondria",
      C:"PCR amplification bias", C_en:"PCR amplification bias",
      D:"解離試劑特異性破壞 mRNA", D_en:"Dissociation reagent damages mRNA",
      ans:"B", exp:"心肌細胞代謝極高，需用組織特異 %mt 閾值。", exp_en:"Cardiomyocytes are highly metabolic; use tissue-specific %mt thresholds." },
    { type:"single", stem:"snRNA-seq 與 scRNA-seq 相較，下列何者正確？", stem_en:"snRNA-seq vs scRNA-seq, which is true?",
      A:"snRNA-seq 偵測較多 mitochondrial 基因", A_en:"snRNA-seq detects more mt genes",
      B:"snRNA-seq 富含未剪接（intronic）reads、mt reads 極少", B_en:"snRNA-seq enriches intronic reads with very few mt reads",
      C:"兩者完全等價", C_en:"They are equivalent",
      D:"snRNA-seq 不能用於 FFPE 樣本", D_en:"snRNA-seq doesn't work on FFPE",
      ans:"B", exp:"核 RNA pool 富含未剪接、mt reads 極少，因此 marker 表達會系統性偏差。", exp_en:"Nuclear RNA pool has many intronic reads and few mt reads, causing marker differences." },
    { type:"single", stem:"細胞解離造成 FOS/JUN/HSPA1A 上調最可能反映？", stem_en:"FOS/JUN/HSPA1A upregulation upon dissociation reflects?",
      A:"解離應激簽名，是技術假象", A_en:"Dissociation-induced stress signature — technical artifact",
      B:"真正的細胞型態", B_en:"A genuine cell type",
      C:"定序錯誤", C_en:"Sequencing error",
      D:"PCR 重複", D_en:"PCR duplicates",
      ans:"A", exp:"解離應激會誘發 immediate early genes 與 heat shock 蛋白，需識別並校正。", exp_en:"Dissociation induces IEGs and HSPs — identify and regress out." },
    { type:"single", stem:"哪一胞器含有自己的 DNA、編碼 13 個 OXPHOS 蛋白？", stem_en:"Which organelle has its own DNA encoding 13 OXPHOS proteins?",
      A:"Golgi", A_en:"Golgi", B:"Lysosome", B_en:"Lysosome",
      C:"Mitochondrion", C_en:"Mitochondrion", D:"Nucleus only", D_en:"Nucleus only",
      ans:"C", exp:"mtDNA 環狀 ~16.6 kb，編碼 13 蛋白 + 2 rRNA + 22 tRNA。", exp_en:"mtDNA is a 16.6 kb circle encoding 13 proteins, 2 rRNAs, 22 tRNAs." },
    { type:"single", stem:"ER stress 的典型 RNA-seq 簽名包含？", stem_en:"A typical ER stress signature includes?",
      A:"HSPA5/BiP, DDIT3/CHOP, ATF4, XBP1s", A_en:"HSPA5/BiP, DDIT3/CHOP, ATF4, XBP1s",
      B:"CASP3, BAX, BAK1", B_en:"CASP3, BAX, BAK1",
      C:"GPX4, ACSL4", C_en:"GPX4, ACSL4",
      D:"NLRP3, GSDMD", D_en:"NLRP3, GSDMD",
      ans:"A", exp:"未摺疊蛋白反應 (UPR) 由 IRE1/PERK/ATF6 啟動。", exp_en:"UPR is driven by IRE1/PERK/ATF6." },
    { type:"multi", stem:"哪些是真核細胞才有的特徵？（多選）", stem_en:"Which features are eukaryote-only? (Multi)",
      A:"有膜包覆的核", A_en:"Membrane-bound nucleus",
      B:"轉錄與轉譯時空分離", B_en:"Spatially/temporally separated transcription and translation",
      C:"mRNA 5'cap 與 polyA tail", C_en:"5' cap and polyA tail on mRNA",
      D:"環狀基因組", D_en:"Circular genome",
      ans:["A","B","C"], exp:"D 是原核典型；真核 mtDNA/cpDNA 雖也是環狀，但核基因組為線性。", exp_en:"D is the bacterial/archaeal pattern; eukaryotic nuclear genomes are linear (organelle DNAs are circular)." },
    { type:"multi", stem:"哪些情境傾向選 snRNA-seq？（多選）", stem_en:"When to prefer snRNA-seq? (Multi)",
      A:"FFPE 樣本", A_en:"FFPE samples",
      B:"成人腦 / 心 / 骨骼肌等難解離組織", B_en:"Adult brain, heart, skeletal muscle (hard to dissociate)",
      C:"想看細胞表面蛋白", C_en:"Want surface protein measurement",
      D:"避免解離應激造成的 marker 偏差", D_en:"Avoid dissociation-induced marker bias",
      ans:["A","B","D"], exp:"C 應用 CITE-seq / TotalSeq。", exp_en:"For surface proteins use CITE-seq / TotalSeq." },
    { type:"tf", stem:"植物 RNA-seq 也可使用 %cp（葉綠體 RNA 比例）作為品質指標。", stem_en:"Plant RNA-seq can use %cp (chloroplast RNA fraction) as a QC metric.",
      ans:"T", exp:"類似動物的 %mt。", exp_en:"Analogous to %mt in animals." },
    { type:"tf", stem:"使用通用 5% %mt 閾值對所有組織都安全。", stem_en:"A universal 5% %mt cutoff is safe for any tissue.",
      ans:"F", exp:"心肌、肝、肌肉細胞天然 %mt 偏高，需組織特異。", exp_en:"Cardiomyocytes, hepatocytes, muscle have naturally high %mt — adjust per tissue." },
    { type:"single", stem:"分泌型/膜蛋白在質譜中常被低估，主要原因？", stem_en:"Why are secretory/membrane proteins underdetected in MS?",
      A:"訊號分子過小", A_en:"Signaling molecules too small",
      B:"疏水性高、tryptic peptides 少 → 富集不易", B_en:"Hydrophobic with few tryptic peptides → poor enrichment",
      C:"完全不被轉錄", C_en:"Not transcribed",
      D:"沒有編碼基因", D_en:"No genes encode them",
      ans:"B", exp:"需要 surface proteomics 或 glycoproteomics 富集。", exp_en:"Surface- or glyco-proteomics enrichment is needed." }
  ],
  "Ch.3 四大生物大分子": [
    { type:"single", stem:"polyA-selected RNA-seq 最主要遺失的 RNA 是？", stem_en:"polyA-selected RNA-seq mostly misses?",
      A:"編碼蛋白的 mRNA", A_en:"Protein-coding mRNA",
      B:"polyA 化的 lncRNA", B_en:"PolyA-tailed lncRNA",
      C:"rRNA、tRNA、circRNA、多數 miRNA", C_en:"rRNA, tRNA, circRNA, most miRNAs",
      D:"任何 RNA", D_en:"All RNA",
      ans:"C", exp:"無 polyA tail 的 RNA 通通被遺失。", exp_en:"RNAs without polyA tails are not captured." },
    { type:"single", stem:"蛋白質四級結構 (quaternary structure) 指什麼？", stem_en:"Quaternary structure means?",
      A:"序列", A_en:"Sequence",
      B:"α-helix 與 β-sheet", B_en:"α-helix and β-sheet",
      C:"單一肽鏈的 3D 摺疊", C_en:"3D fold of one chain",
      D:"多條肽鏈組裝（subunits）", D_en:"Assembly of multiple subunits",
      ans:"D", exp:"四級結構是多 chain 組合（如 hemoglobin 4 subunits）。", exp_en:"Quaternary = multi-chain assembly (e.g. hemoglobin)." },
    { type:"single", stem:"ABO 血型抗原差異的化學基礎是？", stem_en:"Chemical basis of ABO antigen differences?",
      A:"mRNA 量不同", A_en:"Different mRNA levels",
      B:"蛋白質胺基酸序列完全不同", B_en:"Completely different protein sequences",
      C:"醣基轉移酶活性差異造成不同末端糖鏈", C_en:"Glycosyltransferase activity differences add different terminal sugars",
      D:"磷酸化差異", D_en:"Phosphorylation differences",
      ans:"C", exp:"ABO 基因編碼不同活性的 glycosyltransferase。", exp_en:"ABO encodes glycosyltransferases with different sugar specificities." },
    { type:"single", stem:"DNA 與 RNA 化學結構的關鍵差異是？", stem_en:"Key chemical difference between DNA and RNA?",
      A:"DNA 含 U、RNA 含 T", A_en:"DNA has U, RNA has T",
      B:"RNA 在戊糖 2' 位多一個 OH，且用 U 替代 T", B_en:"RNA has 2'-OH and uses U instead of T",
      C:"DNA 為單股、RNA 為雙股", C_en:"DNA is single-stranded, RNA double-stranded",
      D:"RNA 不含氮鹼基", D_en:"RNA has no nitrogenous bases",
      ans:"B", exp:"deoxy-ribose（DNA, 2'-H）vs ribose（RNA, 2'-OH）；DNA 用 T、RNA 用 U。", exp_en:"Deoxyribose (DNA, 2'-H) vs ribose (RNA, 2'-OH); DNA uses T, RNA uses U." },
    { type:"single", stem:"PCR primer 設計時，GC% 推薦範圍是？", stem_en:"Recommended GC% for PCR primers?",
      A:"5–10%", A_en:"5–10%",
      B:"45–60%", B_en:"45–60%",
      C:"95–99%", C_en:"95–99%",
      D:"無關緊要", D_en:"Irrelevant",
      ans:"B", exp:"過低不穩、過高自我複性。", exp_en:"Too low = unstable; too high = self-annealing." },
    { type:"multi", stem:"以下哪些屬於蛋白功能類別？（多選）", stem_en:"Which are protein functional classes? (Multi)",
      A:"酵素", A_en:"Enzymes",
      B:"結構蛋白", B_en:"Structural",
      C:"訊號蛋白", C_en:"Signaling",
      D:"miRNA", D_en:"miRNA",
      ans:["A","B","C"], exp:"miRNA 是 RNA 不是蛋白。", exp_en:"miRNA is RNA, not protein." },
    { type:"multi", stem:"以下哪些是脂質類別？（多選）", stem_en:"Which are lipid classes? (Multi)",
      A:"脂肪酸", A_en:"Fatty acids",
      B:"磷脂（PC/PE/PS/PI）", B_en:"Phospholipids (PC/PE/PS/PI)",
      C:"固醇", C_en:"Sterols",
      D:"胺基酸", D_en:"Amino acids",
      ans:["A","B","C"], exp:"胺基酸是蛋白質單體。", exp_en:"Amino acids are protein monomers." },
    { type:"tf", stem:"AlphaFold 預測之蛋白構象在 PAE 矩陣顯示高不確定區間時，仍可信賴 inter-domain 相對位置。", stem_en:"When AlphaFold's PAE matrix shows high uncertainty between domains, inter-domain orientation is still trustworthy.",
      ans:"F", exp:"PAE 高代表域間相對位置不可信。", exp_en:"High PAE = unreliable inter-domain placement." },
    { type:"tf", stem:"miRNA 通常長度約 22 nt，作用為基因沉默。", stem_en:"miRNAs are ~22 nt and function in gene silencing.",
      ans:"T", exp:"成熟 miRNA ~22 nt，透過與 mRNA 3'UTR 配對抑制翻譯/降解。", exp_en:"Mature miRNAs are ~22 nt and pair with mRNA 3'UTRs to repress translation/degrade." },
    { type:"single", stem:"以下何者是核糖體最主要的催化分子？", stem_en:"What is the main catalytic molecule in the ribosome?",
      A:"蛋白", A_en:"Protein",
      B:"rRNA（核糖體是 ribozyme）", B_en:"rRNA (ribosome is a ribozyme)",
      C:"DNA", C_en:"DNA",
      D:"脂質", D_en:"Lipids",
      ans:"B", exp:"催化中心由 rRNA 主導。", exp_en:"The peptidyl transferase center is RNA-based." }
  ],
  "Ch.4 DNA、染色質與染色體": [
    { type:"single", stem:"ATAC-seq 訊號最強的區域是？", stem_en:"Where is ATAC-seq signal strongest?",
      A:"緊密 heterochromatin", A_en:"Tightly packed heterochromatin",
      B:"染色質開放區（活躍 promoter/enhancer）", B_en:"Open chromatin (active promoters/enhancers)",
      C:"centromere α-satellite", C_en:"Centromeric α-satellite",
      D:"telomere", D_en:"Telomere",
      ans:"B", exp:"Tn5 切入 nucleosome-free regions。", exp_en:"Tn5 transposase accesses nucleosome-free regions." },
    { type:"single", stem:"Hi-C 熱圖上的『方塊 (block)』最直接對應？", stem_en:"Hi-C heatmap 'blocks' correspond to?",
      A:"核小體位置", A_en:"Nucleosomes",
      B:"染色體 p/q 臂", B_en:"p/q arms",
      C:"TADs", C_en:"TADs",
      D:"PCR 重複", D_en:"PCR duplicates",
      ans:"C", exp:"TAD 內 contacts 富集成方塊。", exp_en:"Intra-TAD contacts form blocks." },
    { type:"single", stem:"telomere 重複序列為？", stem_en:"Human telomere repeat?",
      A:"AGCT", A_en:"AGCT", B:"TTAGGG", B_en:"TTAGGG",
      C:"CGGAAC", C_en:"CGGAAC", D:"GCGCGC", D_en:"GCGCGC",
      ans:"B", exp:"人類 telomere = TTAGGG 重複。", exp_en:"Human telomere = TTAGGG repeats." },
    { type:"single", stem:"核小體的組蛋白組成是？", stem_en:"Nucleosome histone composition?",
      A:"H1 ×8", A_en:"H1 ×8",
      B:"H2A、H2B、H3、H4 各 2 個（八聚體）", B_en:"H2A, H2B, H3, H4 ×2 each (octamer)",
      C:"只有 H3 和 H4", C_en:"H3 and H4 only",
      D:"H1、H2A、H3、H4 各 4 個", D_en:"H1, H2A, H3, H4 ×4 each",
      ans:"B", exp:"~146 bp DNA 環繞八聚體 1.65 圈。", exp_en:"~146 bp DNA wraps the octamer 1.65 turns." },
    { type:"single", stem:"短讀比對在 centromere / telomere / segmental dup 區域常失敗，主因？", stem_en:"Short-read alignment often fails at centromeres/telomeres/segmental dup because?",
      A:"GC% 過高", A_en:"GC% too high",
      B:"區域沒有基因", B_en:"No genes there",
      C:"重複序列多 → multi-mapping reads", C_en:"Heavy repeats → multi-mappers",
      D:"DNA 易斷", D_en:"DNA breaks easily",
      ans:"C", exp:"long-read 或 graph genome 可解決。", exp_en:"Long-read or graph genomes help." },
    { type:"multi", stem:"哪些屬於 euchromatin marks？（多選）", stem_en:"Which marks define euchromatin? (Multi)",
      A:"H3K4me3", A_en:"H3K4me3",
      B:"H3K27ac", B_en:"H3K27ac",
      C:"H3K9me3", C_en:"H3K9me3",
      D:"H3K36me3", D_en:"H3K36me3",
      ans:["A","B","D"], exp:"H3K9me3 是 heterochromatin。", exp_en:"H3K9me3 marks heterochromatin." },
    { type:"multi", stem:"關於 T2T-CHM13（2022）正確的描述？（多選）", stem_en:"Which statements about T2T-CHM13 (2022) are correct? (Multi)",
      A:"完成 centromere 與 telomere 完整組裝", A_en:"Assembled centromeres and telomeres",
      B:"填補了 GRCh38 約 8% 的 gap", B_en:"Closed ~8% of GRCh38 gaps",
      C:"是小鼠基因組", C_en:"It is the mouse genome",
      D:"提升 short-read 在重複區的比對信賴度", D_en:"Improves short-read confidence in repeat regions",
      ans:["A","B","D"], exp:"T2T-CHM13 是人類細胞株來源。", exp_en:"T2T-CHM13 derives from a hydatidiform mole cell line of human." },
    { type:"tf", stem:"核小體間 linker DNA 通常 20–80 bp。", stem_en:"Linker DNA between nucleosomes is typically 20–80 bp.",
      ans:"T", exp:"加上核心 146 bp 約 166–226 bp/nucleosome。", exp_en:"Plus the 146 bp core, ~166–226 bp per nucleosome." },
    { type:"tf", stem:"GC 含量高的區域熔解溫度（Tm）較低。", stem_en:"GC-rich regions have lower Tm.",
      ans:"F", exp:"GC 對有 3 個氫鍵更穩，Tm 較高。", exp_en:"GC base pairs have 3 H-bonds — higher Tm." },
    { type:"single", stem:"關於 loop extrusion 模型，下列何者正確？", stem_en:"About loop extrusion model, which is correct?",
      A:"由 RNA polymerase 推動", A_en:"Driven by RNA polymerase",
      B:"由 CTCF / cohesin 介導，解釋 TAD 形成", B_en:"Mediated by CTCF / cohesin, explains TAD formation",
      C:"與基因組組裝無關", C_en:"Unrelated to genome architecture",
      D:"僅在 prokaryote 出現", D_en:"Only in prokaryotes",
      ans:"B", exp:"loop extrusion 是 TAD 形成的物理模型。", exp_en:"Loop extrusion is the physical model for TAD formation." }
  ]
},

"Block B 中心法則": {
  "Ch.5 DNA 複製與修復": [
    { type:"single", stem:"Okazaki 片段存在的根本原因？", stem_en:"Why do Okazaki fragments exist?",
      A:"加快 splicing", A_en:"Speed up splicing",
      B:"DNA pol 只能 5'→3' 延伸，lagging 股需多次起始", B_en:"DNA pol extends only 5'→3'; the lagging strand needs repeated priming",
      C:"使 DNA 形成環", C_en:"To produce circular DNA",
      D:"ribosome 解離產物", D_en:"Byproduct of ribosome dissociation",
      ans:"B", exp:"是 5'→3' 限制下的必然結果。", exp_en:"A direct consequence of the 5'→3' restriction." },
    { type:"single", stem:"Lynch syndrome 腫瘤對 ICI 反應佳，原因是？", stem_en:"Why Lynch syndrome tumors respond to ICIs?",
      A:"DNA 完全沒有突變", A_en:"No mutations at all",
      B:"MSI-H、新抗原多、免疫原性強", B_en:"MSI-H, high neoantigen load, highly immunogenic",
      C:"BRCA1/2 失活", C_en:"BRCA1/2 inactivation",
      D:"上皮細胞無 MHC", D_en:"Epithelial cells lack MHC",
      ans:"B", exp:"MMR 缺陷 → 高 TMB → ICI 敏感。", exp_en:"MMR loss → high TMB → ICI-sensitive." },
    { type:"single", stem:"C>A 在 CC 上下文是哪一簽名？", stem_en:"C>A in CC context corresponds to which signature?",
      A:"UV (SBS7)", A_en:"UV (SBS7)",
      B:"菸草煙 (SBS4)", B_en:"Tobacco smoke (SBS4)",
      C:"APOBEC (SBS2/13)", C_en:"APOBEC (SBS2/13)",
      D:"HRD (SBS3)", D_en:"HRD (SBS3)",
      ans:"B", exp:"SBS4 是肺癌中典型的菸草煙簽名。", exp_en:"SBS4 is the canonical tobacco signature in lung cancer." },
    { type:"single", stem:"PARP inhibitor 的標靶適應症是？", stem_en:"PARP inhibitor target indication?",
      A:"MMR 缺陷腫瘤", A_en:"MMR-deficient tumors",
      B:"HR 缺陷（BRCA1/2、BRCAness、HRD）", B_en:"HR-deficient (BRCA1/2, BRCAness, HRD)",
      C:"高 TMB 腫瘤", C_en:"High-TMB tumors",
      D:"高 MSI 腫瘤", D_en:"MSI-H tumors",
      ans:"B", exp:"synthetic lethality 經典例。", exp_en:"Classic synthetic lethality." },
    { type:"single", stem:"哪一修復通路專責 UV pyrimidine dimer？", stem_en:"Which pathway handles UV pyrimidine dimers?",
      A:"MMR", A_en:"MMR", B:"BER", B_en:"BER",
      C:"NER", C_en:"NER", D:"HR", D_en:"HR",
      ans:"C", exp:"NER 處理 bulky adducts 含 UV dimer；XP 病人 NER 缺陷。", exp_en:"NER handles bulky adducts including UV dimers; XP patients are NER-deficient." },
    { type:"multi", stem:"哪些屬於修復 DSB 的通路？（多選）", stem_en:"Which pathways repair DSBs? (Multi)",
      A:"HR", A_en:"HR",
      B:"NHEJ", B_en:"NHEJ",
      C:"MMR", C_en:"MMR",
      D:"NER", D_en:"NER",
      ans:["A","B"], exp:"MMR 處理 mismatch；NER 處理 bulky lesion。", exp_en:"MMR repairs mismatches; NER repairs bulky lesions." },
    { type:"multi", stem:"哪些是 HR 缺陷腫瘤的特徵？（多選）", stem_en:"Features of HR-deficient tumors? (Multi)",
      A:"SBS3 簽名", A_en:"SBS3 signature",
      B:"BRCA1/2 LoF", B_en:"BRCA1/2 LoF",
      C:"PARP inhibitor 敏感", C_en:"PARP inhibitor sensitive",
      D:"MSI-H", D_en:"MSI-H",
      ans:["A","B","C"], exp:"MSI-H 是 MMR 缺陷腫瘤的特徵。", exp_en:"MSI-H is MMR-deficient, not HR-deficient." },
    { type:"tf", stem:"BRCAness 表型可在無 BRCA1/2 突變的腫瘤上出現。", stem_en:"BRCAness can occur in tumors without BRCA1/2 mutations.",
      ans:"T", exp:"如 promoter 甲基化、PALB2 / RAD51 突變等。", exp_en:"Caused e.g. by promoter methylation, PALB2/RAD51 mutation." },
    { type:"tf", stem:"每個有絲分裂約留下 ~3 個新生突變。", stem_en:"~3 new mutations remain per mitosis on average.",
      ans:"T", exp:"包含 proofreading 與 MMR 後的最終 error rate ~10⁻¹⁰。", exp_en:"After proofreading + MMR, final error rate is ~10⁻¹⁰." },
    { type:"single", stem:"replication timing 與 mutation rate 的關係？", stem_en:"Relationship between replication timing and mutation rate?",
      A:"完全無關", A_en:"Unrelated",
      B:"晚複製區突變率較高（dNTP 耗盡 / 修復下降）", B_en:"Late-replicating regions have higher mutation rates (dNTP depletion / lower repair)",
      C:"早複製區突變率較高", C_en:"Early-replicating regions are higher",
      D:"與性別有關", D_en:"Sex-dependent",
      ans:"B", exp:"晚複製區是腫瘤突變熱點之一。", exp_en:"Late-replicating regions are mutation hotspots in cancer." }
  ],
  "Ch.6 轉錄與 RNA 加工": [
    { type:"single", stem:"5' cap 的主要功能？", stem_en:"Main function of 5' cap?",
      A:"做 splicing branch point", A_en:"Provide branch point",
      B:"保護 mRNA 免於外切酶；招募 eIF4E 啟動轉譯", B_en:"Protect from exonucleases; recruit eIF4E for translation",
      C:"作為 polyA tail 的模板", C_en:"Template for polyA",
      D:"編碼第一個胺基酸", D_en:"Encode first aa",
      ans:"B", exp:"m7G cap 是 mRNA 穩定性與翻譯起始的關鍵。", exp_en:"m7G cap stabilizes mRNA and starts translation." },
    { type:"single", stem:"PSI 在替代剪接分析中代表？", stem_en:"PSI means?",
      A:"Pol II 磷酸化比例", A_en:"Pol II phosphorylation",
      B:"Peptide spectral identification", B_en:"Peptide spectral identification",
      C:"Percent Spliced In", C_en:"Percent Spliced In",
      D:"Protein structure index", D_en:"Protein structure index",
      ans:"C", exp:"PSI 是替代剪接定量的核心指標。", exp_en:"PSI is the core splicing quantification metric." },
    { type:"single", stem:"為什麼 polyA selection 無法捕獲 circRNA？", stem_en:"Why doesn't polyA selection capture circRNAs?",
      A:"circRNA 太短", A_en:"circRNAs too short",
      B:"circRNA 沒有 polyA tail（back-splicing 環狀）", B_en:"circRNAs lack polyA tails (back-splicing produces circles)",
      C:"circRNA 不存在於胞質", C_en:"circRNAs not in cytoplasm",
      D:"circRNA 被甲基化", D_en:"circRNAs methylated",
      ans:"B", exp:"需 rRNA depletion + RNase R 才能富集。", exp_en:"Use rRNA depletion + RNase R for enrichment." },
    { type:"single", stem:"Pol II promoter-proximal pausing 的主因？", stem_en:"What drives Pol II promoter-proximal pausing?",
      A:"DNA 損傷", A_en:"DNA damage",
      B:"NELF / DSIF 暫停因子；P-TEFb 磷酸化 Ser2 後釋放", B_en:"NELF/DSIF pause factors; P-TEFb phosphorylates Ser2 to release",
      C:"miRNA 結合", C_en:"miRNA binding",
      D:"5' cap 缺失", D_en:"Missing 5' cap",
      ans:"B", exp:"Pol II Ser2-P 是 elongation 的指標。", exp_en:"Pol II Ser2-P marks elongation." },
    { type:"single", stem:"3' Tag-seq 最適合用來研究？", stem_en:"3' Tag-seq is best for?",
      A:"isoform 解析", A_en:"isoform resolution",
      B:"APA / 簡單基因表達定量（低成本）", B_en:"APA / cheap gene expression quantitation",
      C:"miRNA 富集", C_en:"miRNA enrichment",
      D:"染色質可及性", D_en:"Chromatin accessibility",
      ans:"B", exp:"只讀 3' 末端，無 isoform 解析力但便宜。", exp_en:"Reads only 3' end — cheap but no isoform resolution." },
    { type:"multi", stem:"以下哪些為替代剪接事件類型？（多選）", stem_en:"Which are AS event types? (Multi)",
      A:"SE (skipped exon)", A_en:"SE (skipped exon)",
      B:"A5SS / A3SS", B_en:"A5SS / A3SS",
      C:"RI (retained intron)", C_en:"RI (retained intron)",
      D:"phosphorylation", D_en:"Phosphorylation",
      ans:["A","B","C"], exp:"Phosphorylation 是 PTM。", exp_en:"Phosphorylation is a PTM, not an AS event." },
    { type:"multi", stem:"以下哪些是 spliceosome 組件？（多選）", stem_en:"Spliceosome components? (Multi)",
      A:"U1 snRNP", A_en:"U1 snRNP",
      B:"U2 snRNP", B_en:"U2 snRNP",
      C:"U6 snRNP", C_en:"U6 snRNP",
      D:"ribosome", D_en:"Ribosome",
      ans:["A","B","C"], exp:"剪接體 = U1/U2/U4/U5/U6 + 蛋白；ribosome 是轉譯機器。", exp_en:"Spliceosome = U1/U2/U4/U5/U6 + proteins; ribosome is for translation." },
    { type:"tf", stem:"超過 90% 的人類多 exon 基因發生替代剪接。", stem_en:">90% of human multi-exon genes undergo alternative splicing.",
      ans:"T", exp:"Pan et al. (2008) 估算。", exp_en:"Pan et al. (2008) estimate." },
    { type:"tf", stem:"RNA pol II 也轉錄 rRNA。", stem_en:"RNA pol II transcribes rRNA.",
      ans:"F", exp:"rRNA 由 Pol I（在核仁）轉錄；Pol II 轉錄 mRNA 與多數 ncRNA。", exp_en:"rRNA is transcribed by Pol I in the nucleolus; Pol II transcribes mRNA and most ncRNAs." },
    { type:"single", stem:"H3K4me3 通常標記？", stem_en:"H3K4me3 typically marks?",
      A:"活躍 promoter (TSS ±1 kb)", A_en:"Active promoters (TSS ±1 kb)",
      B:"heterochromatin", B_en:"Heterochromatin",
      C:"telomere", C_en:"Telomere",
      D:"polyA tail", D_en:"PolyA tail",
      ans:"A", exp:"由 MLL/KMT2 家族寫入。", exp_en:"Written by MLL/KMT2 family." }
  ],
  "Ch.7 轉譯與蛋白質結構": [
    { type:"single", stem:"mRNA 與蛋白質相關係數常僅 0.4–0.6，原因是？", stem_en:"Why mRNA-protein correlation is only ~0.4–0.6?",
      A:"mRNA 量測錯誤多", A_en:"mRNA noisy",
      B:"翻譯效率、半衰期、PTM、定位、降解 多層解耦", B_en:"Translation efficiency, half-lives, PTMs, localization, degradation decouple",
      C:"蛋白不存在", C_en:"Proteins not real",
      D:"RNA-seq 與 MS 都不準", D_en:"Both methods inaccurate",
      ans:"B", exp:"多層調控解耦是根本原因。", exp_en:"Multi-layer regulation is the root cause." },
    { type:"single", stem:"AlphaFold 預測時最重要的兩個信心指標？", stem_en:"Two key AlphaFold confidence metrics?",
      A:"RMSD + p-value", A_en:"RMSD + p-value",
      B:"pLDDT（每殘基）+ PAE（域間）", B_en:"pLDDT (per-residue) + PAE (inter-domain)",
      C:"BLAST e-value", C_en:"BLAST e-value",
      D:"GC%", D_en:"GC%",
      ans:"B", exp:"pLDDT 與 PAE 是 AlphaFold 使用者必看。", exp_en:"pLDDT and PAE are essential for AlphaFold use." },
    { type:"single", stem:"Ribo-seq 主要量到？", stem_en:"What does Ribo-seq capture?",
      A:"染色質結構", A_en:"Chromatin structure",
      B:"DNA 甲基化", B_en:"DNA methylation",
      C:"ribosome 保護下的 28-32 nt mRNA 片段（指出活躍翻譯位置）", C_en:"28–32 nt mRNA fragments protected by ribosomes — actively translated positions",
      D:"蛋白濃度", D_en:"Protein concentration",
      ans:"C", exp:"Ribo-seq 揭示翻譯位置與效率。", exp_en:"Ribo-seq reveals translation position and efficiency." },
    { type:"single", stem:"標準遺傳密碼 (genetic code) 的特性？", stem_en:"Genetic code feature?",
      A:"完全 1:1（無 degeneracy）", A_en:"Strictly 1:1, no degeneracy",
      B:"簡並性：多個 codon 編同一胺基酸", B_en:"Degenerate: multiple codons encode the same aa",
      C:"4 個 codon", C_en:"Has only 4 codons",
      D:"無起始 codon", D_en:"No start codon",
      ans:"B", exp:"64 codon = 61 sense + 3 stop；多個 codon 對應同一 aa。", exp_en:"64 codons = 61 sense + 3 stop; degeneracy allows multiple codons per aa." },
    { type:"single", stem:"UPR (Unfolded Protein Response) 的主要感受器？", stem_en:"Main UPR sensors?",
      A:"p53、ATM、BRCA1", A_en:"p53, ATM, BRCA1",
      B:"IRE1、PERK、ATF6", B_en:"IRE1, PERK, ATF6",
      C:"TLR4、MYD88", C_en:"TLR4, MYD88",
      D:"E2F1、Rb", D_en:"E2F1, Rb",
      ans:"B", exp:"ER stress 主要由這三個感受器啟動下游 TF。", exp_en:"ER stress triggers IRE1, PERK, ATF6 to activate downstream TFs." },
    { type:"multi", stem:"以下哪些是核糖體 (ribosome) 構成成分？（多選）", stem_en:"Ribosome components? (Multi)",
      A:"60S 大亞單位（含 28S/5.8S/5S rRNA）", A_en:"60S large subunit (28S/5.8S/5S rRNA)",
      B:"40S 小亞單位（含 18S rRNA）", B_en:"40S small subunit (18S rRNA)",
      C:"ribosome proteins", C_en:"Ribosomal proteins",
      D:"DNA polymerase", D_en:"DNA polymerase",
      ans:["A","B","C"], exp:"DNA pol 與翻譯無關。", exp_en:"DNA pol is for replication." },
    { type:"multi", stem:"哪些蛋白伴侶系統可協助摺疊？（多選）", stem_en:"Chaperone systems assisting folding? (Multi)",
      A:"Hsp70", A_en:"Hsp70",
      B:"Hsp60 / GroEL", B_en:"Hsp60 / GroEL",
      C:"Hsp90", C_en:"Hsp90",
      D:"caspase-3", D_en:"caspase-3",
      ans:["A","B","C"], exp:"caspase-3 是 apoptosis 執行者。", exp_en:"Caspase-3 executes apoptosis." },
    { type:"tf", stem:"AlphaFold 可預測蛋白與 ligand 結合的精確構象。", stem_en:"AlphaFold can predict precise ligand-binding poses.",
      ans:"F", exp:"AF2 不預測 ligand pose；AF3 雖含 ligand 但仍有限。", exp_en:"AF2 doesn't predict ligand poses; AF3 includes ligands but accuracy is limited." },
    { type:"tf", stem:"轉譯起始時，40S 與 mRNA 結合並掃描 5'UTR 找 AUG（Kozak 上下文）。", stem_en:"40S scans 5'UTR for AUG in a Kozak context during initiation.",
      ans:"T", exp:"是 cap-dependent 起始的標準機制。", exp_en:"Standard cap-dependent initiation." },
    { type:"single", stem:"K48 polyubiquitin chain 主要目標蛋白命運是？", stem_en:"K48 polyubiquitin chain marks protein for?",
      A:"autophagy", A_en:"Autophagy",
      B:"proteasome 降解", B_en:"Proteasomal degradation",
      C:"分泌", C_en:"Secretion",
      D:"轉錄活化", D_en:"Transcriptional activation",
      ans:"B", exp:"K48 是 proteasome 招募訊號；K63 與 autophagy / 訊號傳遞相關。", exp_en:"K48 signals proteasome; K63 relates to autophagy/signaling." }
  ],
  "Ch.8 基因表達調控": [
    { type:"single", stem:"scATAC + scRNA 的主要動機？", stem_en:"Why combine scATAC + scRNA?",
      A:"提高 read 數", A_en:"More reads",
      B:"補上染色質可及性 / TF 結合潛力層", B_en:"Add accessibility + TF binding potential layer",
      C:"解決 doublet", C_en:"Solve doublets",
      D:"提升解離效率", D_en:"Improve dissociation",
      ans:"B", exp:"兩層整合可推 GRN。", exp_en:"Combined data enables GRN inference." },
    { type:"single", stem:"SCENIC 的主要輸出？", stem_en:"SCENIC outputs?",
      A:"變異註解", A_en:"Variant annotation",
      B:"細胞表面蛋白", B_en:"Surface protein",
      C:"Regulon + per-cell AUC TF 活性分數", C_en:"Regulons + per-cell AUC TF activity",
      D:"variant calling", D_en:"Variant calling",
      ans:"C", exp:"SCENIC 提取 regulon 並評每細胞 TF 活性。", exp_en:"SCENIC extracts regulons and scores TF activity per cell." },
    { type:"single", stem:"mRNA 上升但蛋白不變，最可能反映？", stem_en:"mRNA up but protein unchanged reflects?",
      A:"翻譯效率下降、蛋白降解或 miRNA 抑制", A_en:"Lower TE, faster degradation, or miRNA repression",
      B:"DNA 突變", B_en:"DNA mutation",
      C:"染色質關閉", C_en:"Reduced accessibility",
      D:"PCR bias", D_en:"PCR bias",
      ans:"A", exp:"post-transcriptional / post-translational 調控解耦。", exp_en:"Post-transcriptional or translational decoupling." },
    { type:"single", stem:"DNase-seq vs ATAC-seq 的關鍵差異？", stem_en:"Difference between DNase-seq and ATAC-seq?",
      A:"完全相同", A_en:"Identical",
      B:"DNase 用 DNase I 切；ATAC 用 Tn5 同時切並接 adapter", B_en:"DNase uses DNase I; ATAC uses Tn5 to cut and tag in one step",
      C:"DNase 偵測 protein 結合", C_en:"DNase measures protein binding",
      D:"ATAC 偵測甲基化", D_en:"ATAC measures methylation",
      ans:"B", exp:"ATAC-seq 步驟簡化、起始量低（5K cells）。", exp_en:"ATAC simplifies workflow and needs fewer cells (~5K)." },
    { type:"single", stem:"H3K27me3 由誰寫入？", stem_en:"H3K27me3 is written by?",
      A:"MLL/KMT2", A_en:"MLL/KMT2",
      B:"PRC2 (EZH2)", B_en:"PRC2 (EZH2)",
      C:"SUV39H", C_en:"SUV39H",
      D:"P300", D_en:"P300",
      ans:"B", exp:"PRC2 介導 facultative heterochromatin。", exp_en:"PRC2 establishes facultative heterochromatin." },
    { type:"multi", stem:"哪些 RBP-相關技術？（多選）", stem_en:"Which are RBP-related assays? (Multi)",
      A:"CLIP", A_en:"CLIP",
      B:"eCLIP", B_en:"eCLIP",
      C:"iCLIP", C_en:"iCLIP",
      D:"ChIP-seq", D_en:"ChIP-seq",
      ans:["A","B","C"], exp:"ChIP-seq 是 DNA-protein 結合，不是 RBP。", exp_en:"ChIP-seq is for DNA-binding proteins, not RBPs." },
    { type:"multi", stem:"以下哪些是調控 mRNA 命運的因素？（多選）", stem_en:"Which influence mRNA fate? (Multi)",
      A:"3'UTR miRNA 結合位點", A_en:"3'UTR miRNA binding sites",
      B:"RBP（如 ELAVL1, HuR）", B_en:"RBPs (e.g. ELAVL1, HuR)",
      C:"m6A 修飾", C_en:"m6A modification",
      D:"染色體核型", D_en:"Chromosome karyotype",
      ans:["A","B","C"], exp:"karyotype 不直接影響成熟 mRNA 命運。", exp_en:"Karyotype doesn't directly affect mature mRNA fate." },
    { type:"tf", stem:"Bivalent domain（H3K4me3 + H3K27me3）多見於分化體細胞 housekeeping 基因。", stem_en:"Bivalent domains (H3K4me3 + H3K27me3) are common in housekeeping genes of differentiated cells.",
      ans:"F", exp:"bivalent 多見於 ESC 的發育基因（primed but not expressed）。", exp_en:"Bivalent domains mark primed developmental genes in ESCs." },
    { type:"tf", stem:"CellOracle 利用 scATAC + scRNA 可推 in-silico TF KO 效應。", stem_en:"CellOracle uses scATAC + scRNA to predict in-silico TF KO effects.",
      ans:"T", exp:"CellOracle 結合染色質與表達建模。", exp_en:"CellOracle integrates chromatin + expression for in-silico perturbation." },
    { type:"single", stem:"H3K9me3 主要與哪一類染色質相關？", stem_en:"H3K9me3 mainly marks?",
      A:"euchromatin", A_en:"Euchromatin",
      B:"constitutive heterochromatin（如重複序列、retroelement 沉默）", B_en:"Constitutive heterochromatin (repeats, retroelement silencing)",
      C:"polyA tail", C_en:"PolyA tail",
      D:"core promoter", D_en:"Core promoter",
      ans:"B", exp:"Writer: SUV39H, SETDB1。", exp_en:"Writers: SUV39H, SETDB1." }
  ]
},

"Block C 基因組、遺傳與細胞調控": {
  "Ch.9 基因組結構與註解": [
    { type:"single", stem:"GENCODE / Ensembl GTF 中沒有顯式 entry 的？", stem_en:"Not an explicit GTF entry?",
      A:"exon", A_en:"exon", B:"CDS", B_en:"CDS",
      C:"intron（需從 exon 間推斷）", C_en:"intron (inferred from exon gaps)",
      D:"transcript", D_en:"transcript",
      ans:"C", exp:"GTF/GFF 不存 intron entry。", exp_en:"GTF/GFF lacks intron entries." },
    { type:"single", stem:"為什麼偽基因（pseudogene）在 RNA-seq 定量需特別注意？", stem_en:"Why pseudogenes need care in RNA-seq?",
      A:"偽基因都是高表達", A_en:"Always high expression",
      B:"reads multi-map 到 paralog 與偽基因之間，影響計數", B_en:"Reads multi-map between pseudogene and parent — biased counts",
      C:"偽基因不會被轉錄", C_en:"Pseudogenes are not transcribed",
      D:"偽基因不在 GTF 內", D_en:"Pseudogenes not in GTF",
      ans:"B", exp:"序列高度相似造成定量誤差。", exp_en:"High sequence similarity causes quantification error." },
    { type:"single", stem:"T2T-CHM13 與 GRCh38 主要差異？", stem_en:"Main difference between T2T-CHM13 and GRCh38?",
      A:"T2T 是 mouse", A_en:"T2T is mouse",
      B:"T2T 完整含 telomere/centromere/acrocentric 短臂；GRCh38 仍有 ~8% gap", B_en:"T2T includes telomeres/centromeres/acrocentric arms; GRCh38 still has ~8% gaps",
      C:"無差別", C_en:"No difference",
      D:"T2T 比 GRCh38 短", D_en:"T2T is shorter",
      ans:"B", exp:"Nurk et al. 2022 完整組裝。", exp_en:"Nurk et al. 2022 fully assembled." },
    { type:"single", stem:"人類基因組中蛋白編碼區占約多少？", stem_en:"Protein-coding regions are ~? of the human genome?",
      A:"~1.5%", A_en:"~1.5%", B:"~10%", B_en:"~10%",
      C:"~50%", C_en:"~50%", D:"~80%", D_en:"~80%",
      ans:"A", exp:"GENCODE 蛋白編碼 exon 約 1–1.5%。", exp_en:"Protein-coding exons make up ~1–1.5%." },
    { type:"single", stem:"人類基因組重複元素佔比約？", stem_en:"Approximate fraction of repetitive elements in human genome?",
      A:"~5%", A_en:"~5%", B:"~20%", B_en:"~20%",
      C:"&gt; 50%", C_en:"&gt;50%", D:"~98%", D_en:"~98%",
      ans:"C", exp:"LINE/SINE/LTR/satellite 加起來超過一半。", exp_en:"LINE/SINE/LTR/satellites together exceed 50%." },
    { type:"multi", stem:"哪些屬於 ENCODE / cCRE 候選順式調控元件分類？（多選）", stem_en:"Which are ENCODE cCRE categories? (Multi)",
      A:"promoter-like signature", A_en:"promoter-like",
      B:"enhancer-like signature", B_en:"enhancer-like",
      C:"CTCF-bound", C_en:"CTCF-bound",
      D:"intron retention", D_en:"intron retention",
      ans:["A","B","C"], exp:"intron retention 是替代剪接事件。", exp_en:"Intron retention is a splicing event." },
    { type:"multi", stem:"以下哪些是基因組註解資料庫？（多選）", stem_en:"Which are genome annotation databases? (Multi)",
      A:"GENCODE", A_en:"GENCODE",
      B:"Ensembl", B_en:"Ensembl",
      C:"RefSeq", C_en:"RefSeq",
      D:"PhosphoSitePlus", D_en:"PhosphoSitePlus",
      ans:["A","B","C"], exp:"PhosphoSitePlus 是 PTM 資料庫。", exp_en:"PhosphoSitePlus is a PTM database." },
    { type:"tf", stem:"GRCh37 (hg19) 已被 GRCh38 完全淘汰，所有資料都已遷移。", stem_en:"GRCh37 (hg19) has been fully replaced; all data migrated.",
      ans:"F", exp:"ClinVar/HGMD 等多數臨床資料仍用 hg19，需要轉換。", exp_en:"Clinical resources (ClinVar/HGMD) often still use hg19 — needs liftover." },
    { type:"tf", stem:"`chr1` 與 `1` 是相同的染色體名，可以互換使用而不需轉換。", stem_en:"`chr1` and `1` are interchangeable without conversion.",
      ans:"F", exp:"UCSC vs Ensembl 命名不同，混用會比對失敗。", exp_en:"UCSC vs Ensembl differ — mixing leads to alignment failure." },
    { type:"single", stem:"smORF / micropeptides 屬於？", stem_en:"smORFs / micropeptides are?",
      A:"傳統蛋白編碼基因", A_en:"Classical coding genes",
      B:"短 ORF（&lt; 100 codon）所編碼的小蛋白，近年成為新註解類別", B_en:"Short ORFs (&lt;100 codons) encoding small peptides — a newer annotation class",
      C:"miRNA 的別稱", C_en:"Another name for miRNA",
      D:"重複序列", D_en:"Repeats",
      ans:"B", exp:"Ribo-seq 揭露 smORFs 的功能性翻譯。", exp_en:"Ribo-seq has revealed translation of many smORFs." }
  ],
  "Ch.10 突變與遺傳變異": [
    { type:"single", stem:"germline het 變異在血液樣本的 VAF 應接近？", stem_en:"Heterozygous germline VAF in blood ≈?",
      A:"0.05", A_en:"0.05", B:"0.5", B_en:"0.5",
      C:"0.1", C_en:"0.1", D:"0.95", D_en:"0.95",
      ans:"B", exp:"雜合 = 1/2 等位帶變異 → VAF ≈ 0.5。", exp_en:"Het = 1 of 2 alleles, VAF ≈ 0.5." },
    { type:"single", stem:"CDS 中一個 1 bp deletion 最可能造成？", stem_en:"A 1-bp deletion in CDS most likely causes?",
      A:"synonymous", A_en:"synonymous",
      B:"missense", B_en:"missense",
      C:"frameshift（多伴 NMD → LoF）", C_en:"frameshift (often NMD → LoF)",
      D:"no effect", D_en:"no effect",
      ans:"C", exp:"1 bp 非 3 倍數 → frame 改變。", exp_en:"1 bp ≠ multiple of 3 → frame shifts." },
    { type:"single", stem:"ACMG/AMP VUS 變異的合適行動？", stem_en:"For ACMG/AMP VUS, the right action?",
      A:"直接做預防性手術", A_en:"Proceed to prophylactic surgery",
      B:"視為 benign", B_en:"Treat as benign",
      C:"不單獨行動；尋找 family segregation / functional study / follow-up", C_en:"Don't act on alone — pursue segregation, functional, or follow-up",
      D:"列為 P 並通報", D_en:"Reclassify to P and report",
      ans:"C", exp:"VUS 沒有足夠證據可單獨行動。", exp_en:"VUS lacks sufficient evidence to act alone." },
    { type:"single", stem:"哪一工具是 missense 變異 in-silico 致病性預測的當前金標準？", stem_en:"Current gold-standard for in-silico missense pathogenicity?",
      A:"GATK", A_en:"GATK",
      B:"REVEL 或 AlphaMissense", B_en:"REVEL or AlphaMissense",
      C:"SpliceAI", C_en:"SpliceAI",
      D:"PLINK", D_en:"PLINK",
      ans:"B", exp:"AlphaMissense (2023) 與 REVEL 是當前主力。", exp_en:"AlphaMissense (2023) and REVEL are widely used." },
    { type:"single", stem:"somatic 變異與 germline 變異最直接的 VAF 差異是？", stem_en:"VAF difference between somatic and germline?",
      A:"somatic 永遠 = 1.0", A_en:"Somatic always 1.0",
      B:"germline 雜合 ≈ 0.5；somatic 通常 0.01–0.5（subclonal）", B_en:"Germline het ≈ 0.5; somatic often 0.01–0.5 (subclonal)",
      C:"germline 必為純合", C_en:"Germline always homozygous",
      D:"無差別", D_en:"No difference",
      ans:"B", exp:"subclonal somatic 通常 VAF 低。", exp_en:"Subclonal somatic variants have lower VAF." },
    { type:"multi", stem:"VCF 標準欄位包含？（多選）", stem_en:"Standard VCF columns include? (Multi)",
      A:"CHROM, POS", A_en:"CHROM, POS",
      B:"REF, ALT", B_en:"REF, ALT",
      C:"FILTER, INFO", C_en:"FILTER, INFO",
      D:"k-mer index", D_en:"k-mer index",
      ans:["A","B","C"], exp:"VCF v4.x 規範主欄位。", exp_en:"Per VCF v4.x spec." },
    { type:"multi", stem:"以下哪些是 SV caller？（多選）", stem_en:"Which are SV callers? (Multi)",
      A:"Manta", A_en:"Manta",
      B:"DELLY", B_en:"DELLY",
      C:"Sniffles2 (long-read)", C_en:"Sniffles2 (long-read)",
      D:"DESeq2", D_en:"DESeq2",
      ans:["A","B","C"], exp:"DESeq2 是 RNA-seq DE 工具。", exp_en:"DESeq2 is for RNA-seq DE." },
    { type:"tf", stem:"HGVS 命名規範可避免變異描述歧義。", stem_en:"HGVS nomenclature avoids ambiguity in variant description.",
      ans:"T", exp:"如 NM_004006.3:c.1521_1523delCTT (p.Phe508del)。", exp_en:"E.g. NM_004006.3:c.1521_1523delCTT (p.Phe508del)." },
    { type:"tf", stem:"大多數 GWAS 顯著位點都落在蛋白編碼區。", stem_en:"Most GWAS hits land in coding regions.",
      ans:"F", exp:"&gt;90% GWAS hits 在非編碼區。", exp_en:">90% of GWAS hits are non-coding." },
    { type:"single", stem:"以下哪一變異類型 short-read 通常難以偵測？", stem_en:"Which variant is hardest for short-read to detect?",
      A:"SNV", A_en:"SNV",
      B:"1 bp indel", B_en:"1 bp indel",
      C:"大型 SV / 重複擴增 / 染色體易位", C_en:"Large SVs / repeat expansions / chromosomal translocations",
      D:"missense", D_en:"Missense",
      ans:"C", exp:"long-read 是大型 SV 偵測的方向。", exp_en:"Long-read is preferred for large SVs." }
  ],
  "Ch.11 遺傳與群體遺傳": [
    { type:"single", stem:"在大樣本族群中 SNP 嚴重偏離 HWE，最不可能的解釋？", stem_en:"In a large cohort, severe HWE deviation is LEAST likely due to?",
      A:"基因分型錯誤", A_en:"Genotyping error",
      B:"族群結構", B_en:"Population structure",
      C:"樣本太大造成微小偏差被偵測到（HWE 實際成立）", C_en:"Large N detects tiny deviations despite HWE holding",
      D:"強選汰", D_en:"Strong selection",
      ans:"C", exp:"樣本大本身不會造成 HWE 失敗。", exp_en:"Large sample size alone doesn't cause HWE failure." },
    { type:"single", stem:"GWAS p &lt; 5×10⁻⁸ 對應？", stem_en:"GWAS p &lt; 5×10⁻⁸ corresponds to?",
      A:"FDR 5%", A_en:"5% FDR",
      B:"Bonferroni 約 100 萬個獨立檢驗", B_en:"Bonferroni for ~1M tests",
      C:"Holm 修正", C_en:"Holm",
      D:"permutation p", D_en:"Permutation p",
      ans:"B", exp:"0.05/10⁶ ≈ 5×10⁻⁸。", exp_en:"0.05/10⁶ ≈ 5×10⁻⁸." },
    { type:"single", stem:"歐裔 PRS 在非歐裔人群效力下降的主因？", stem_en:"Why does European-derived PRS perform worse in non-Europeans?",
      A:"完全無相關性", A_en:"Entirely uncorrelated",
      B:"LD 結構與等位頻率差異", B_en:"Differences in LD and allele frequencies",
      C:"統計效能更佳", C_en:"Higher power",
      D:"檢測方法錯誤", D_en:"Wrong methods",
      ans:"B", exp:"Martin et al. 2019 詳述 PRS 公平性問題。", exp_en:"Martin et al. 2019 detailed PRS equity issues." },
    { type:"single", stem:"Hardy-Weinberg 平衡的核心假設？", stem_en:"Core HWE assumptions?",
      A:"小族群、近親婚配", A_en:"Small population, inbreeding",
      B:"隨機交配、無選汰、無突變、大族群", B_en:"Random mating, no selection/mutation, large population",
      C:"任意條件下都成立", C_en:"Always true",
      D:"只在原核細胞成立", D_en:"Only in prokaryotes",
      ans:"B", exp:"HWE 是理想化條件。", exp_en:"HWE describes idealized conditions." },
    { type:"single", stem:"Mendelian AR 疾病典型遺傳特徵？", stem_en:"Typical Mendelian AR trait?",
      A:"每代都出現", A_en:"Appears every generation",
      B:"父母多為帶因者、近親婚配風險高", B_en:"Parents are carriers; consanguinity raises risk",
      C:"只在男性表現", C_en:"Only in males",
      D:"母系遺傳", D_en:"Maternal inheritance",
      ans:"B", exp:"AR 需雙等位失活；CF / SCA / PKU 為例。", exp_en:"AR needs both alleles affected; CF, SCA, PKU." },
    { type:"multi", stem:"哪些工具用於 GWAS 分析？（多選）", stem_en:"Which tools are used in GWAS? (Multi)",
      A:"PLINK", A_en:"PLINK",
      B:"SAIGE", B_en:"SAIGE",
      C:"REGENIE", C_en:"REGENIE",
      D:"Cellpose", D_en:"Cellpose",
      ans:["A","B","C"], exp:"Cellpose 是細胞影像分析。", exp_en:"Cellpose is for bioimage segmentation." },
    { type:"multi", stem:"哪些屬於族群結構推論方法？（多選）", stem_en:"Methods for inferring population structure? (Multi)",
      A:"PCA", A_en:"PCA",
      B:"ADMIXTURE", B_en:"ADMIXTURE",
      C:"STRUCTURE", C_en:"STRUCTURE",
      D:"DESeq2", D_en:"DESeq2",
      ans:["A","B","C"], exp:"DESeq2 是 DE 分析。", exp_en:"DESeq2 is for DE analysis." },
    { type:"tf", stem:"GWAS 中 lead SNP 必為真實的因果變異 (causal)。", stem_en:"The GWAS lead SNP is always the true causal variant.",
      ans:"F", exp:"LD 可使 lead 與真實 causal 不同；需 fine-mapping。", exp_en:"LD can decouple lead from causal — fine-mapping is needed." },
    { type:"tf", stem:"X-linked recessive 疾病通常男性病多、女性多為帶因者。", stem_en:"X-linked recessive diseases mostly affect males; females are usually carriers.",
      ans:"T", exp:"DMD、血友病、色盲。", exp_en:"DMD, hemophilia, color blindness." },
    { type:"single", stem:"GWAS QC 中常用的 SNP-level QC 項目？", stem_en:"Common GWAS SNP-level QC?",
      A:"call rate, MAF, HWE p-value", A_en:"call rate, MAF, HWE p-value",
      B:"Phred score 平均", B_en:"Average Phred score",
      C:"GC%", C_en:"GC%",
      D:"PCR cycle 數", D_en:"PCR cycle number",
      ans:"A", exp:"標準三項，常還包括 MissingnessDiff between cases/controls。", exp_en:"Standard three, plus missingness diff between cases/controls." }
  ],
  "Ch.12 表觀遺傳": [
    { type:"single", stem:"Promoter CpG island 高甲基化通常意味？", stem_en:"High methylation at promoter CGI usually means?",
      A:"高表達", A_en:"High expression",
      B:"剪接活躍", B_en:"Active splicing",
      C:"基因沉默", C_en:"Silencing",
      D:"父系印記", D_en:"Paternal imprint",
      ans:"C", exp:"CGI 甲基化阻礙 PIC 組裝。", exp_en:"CGI methylation blocks PIC assembly." },
    { type:"single", stem:"Bivalent domain（H3K4me3 + H3K27me3）多見於？", stem_en:"Bivalent domains are common in?",
      A:"ESC 中的發育基因（primed but not expressed）", A_en:"ESC developmental genes (primed but not expressed)",
      B:"分化體細胞 housekeeping 基因", B_en:"Housekeeping genes in differentiated cells",
      C:"偽基因", C_en:"Pseudogenes",
      D:"端粒", D_en:"Telomeres",
      ans:"A", exp:"分化後 bivalent 多會走向一邊。", exp_en:"Bivalency resolves toward one mark upon differentiation." },
    { type:"single", stem:"Nanopore 直接甲基化偵測 vs WGBS，最大優勢？", stem_en:"Biggest advantage of Nanopore native methylation vs WGBS?",
      A:"成本最低", A_en:"Lowest cost",
      B:"無需化學轉換；同步測 sequence + methylation + 單分子 phased haplotype", B_en:"No chemical conversion; reads sequence + methylation + phased haplotype",
      C:"解析度遠高於 WGBS", C_en:"Higher resolution than WGBS",
      D:"只偵測 CGI", D_en:"Only CGI-focused",
      ans:"B", exp:"Simpson et al. 2017 的代表性技術。", exp_en:"Simpson et al. 2017 — landmark method." },
    { type:"single", stem:"XIST lncRNA 的主要作用？", stem_en:"Main role of XIST lncRNA?",
      A:"促進 mRNA 翻譯", A_en:"Promote translation",
      B:"包覆 cis X 染色體啟動 X-inactivation", B_en:"Coat cis X to initiate X-inactivation",
      C:"做 splicing branch point", C_en:"Splicing branch point",
      D:"控制 mtDNA", D_en:"Control mtDNA",
      ans:"B", exp:"XIST 招募 PRC2/PRC1 → H3K27me3 / H2AK119ub。", exp_en:"XIST recruits PRC2/PRC1 → H3K27me3 / H2AK119ub." },
    { type:"single", stem:"Prader-Willi syndrome 與 Angelman syndrome 為何相關？", stem_en:"Why are Prader-Willi and Angelman related?",
      A:"來自相同 X-linked 變異", A_en:"Same X-linked mutation",
      B:"相同 15q11-q13 區段 imprinting 異常；父系或母系缺失不同", B_en:"Same 15q11-q13 imprinted region, but paternal vs maternal loss",
      C:"屬於粒線體疾病", C_en:"Mitochondrial diseases",
      D:"屬於 trisomy 21", D_en:"Both are trisomy 21",
      ans:"B", exp:"父系缺失 → Prader-Willi；母系缺失 → Angelman。", exp_en:"Paternal loss → Prader-Willi; maternal loss → Angelman." },
    { type:"multi", stem:"哪些是 active enhancer 的標誌？（多選）", stem_en:"Active enhancer marks? (Multi)",
      A:"H3K4me1", A_en:"H3K4me1",
      B:"H3K27ac", B_en:"H3K27ac",
      C:"ATAC-seq 開放訊號", C_en:"ATAC-seq open signal",
      D:"H3K9me3", D_en:"H3K9me3",
      ans:["A","B","C"], exp:"H3K9me3 是 heterochromatin。", exp_en:"H3K9me3 marks heterochromatin." },
    { type:"multi", stem:"以下哪些屬於 epigenetic clocks？（多選）", stem_en:"Which are epigenetic clocks? (Multi)",
      A:"Horvath 2013", A_en:"Horvath 2013",
      B:"PhenoAge", B_en:"PhenoAge",
      C:"GrimAge", C_en:"GrimAge",
      D:"AlphaFold", D_en:"AlphaFold",
      ans:["A","B","C"], exp:"AlphaFold 是蛋白結構預測。", exp_en:"AlphaFold predicts protein structure." },
    { type:"tf", stem:"DNA methylation 是動態調控，可由 TET 家族去甲基化。", stem_en:"DNA methylation is dynamic; TET enzymes drive demethylation.",
      ans:"T", exp:"TET1/2/3 將 5mC → 5hmC → 5fC → 5caC → DNA repair 移除。", exp_en:"TET1/2/3 oxidize 5mC stepwise; final removal via repair." },
    { type:"tf", stem:"WGBS 直接讀取 5mC 而不需任何化學處理。", stem_en:"WGBS reads 5mC directly without chemistry.",
      ans:"F", exp:"WGBS 用 bisulfite 化學轉換；Nanopore 才是直接讀。", exp_en:"WGBS uses bisulfite; Nanopore reads natively." },
    { type:"single", stem:"Gene-body 甲基化通常與？", stem_en:"Gene-body methylation typically correlates with?",
      A:"基因沉默", A_en:"Gene silencing",
      B:"活躍轉錄並影響剪接", B_en:"Active transcription and splicing modulation",
      C:"端粒延長", C_en:"Telomere elongation",
      D:"細胞凋亡", D_en:"Apoptosis",
      ans:"B", exp:"Gene-body methylation 與 active transcription 共存。", exp_en:"Gene-body methylation co-occurs with active transcription." }
  ],
  "Ch.13 細胞週期、分裂與訊號": [
    { type:"single", stem:"CellCycleScoring 在 scRNA-seq 上的主要功能？", stem_en:"CellCycleScoring's main role in scRNA-seq?",
      A:"偵測 doublets", A_en:"Detect doublets",
      B:"偵測 mt 比例", B_en:"Detect %mt",
      C:"估算每細胞 S 與 G2/M 分數，必要時 regress out", C_en:"Estimate per-cell S and G2/M scores; regress out",
      D:"計算 PRS", D_en:"Compute PRS",
      ans:"C", exp:"基於 Tirosh 2016 markers。", exp_en:"Uses Tirosh 2016 markers." },
    { type:"single", stem:"KRAS G12C 突變腫瘤近年的標靶藥？", stem_en:"Targeted drugs for KRAS G12C mutant tumors?",
      A:"PARP inhibitors", A_en:"PARP inhibitors",
      B:"sotorasib / adagrasib（共價 G12C 抑制劑）", B_en:"sotorasib / adagrasib (covalent G12C inhibitors)",
      C:"JAK inhibitors", C_en:"JAK inhibitors",
      D:"EZH2 inhibitors", D_en:"EZH2 inhibitors",
      ans:"B", exp:"近五年精準腫瘤學的里程碑。", exp_en:"Recent precision-oncology breakthrough." },
    { type:"single", stem:"細胞老化（senescence）標準簽名包含？", stem_en:"Senescence signature includes?",
      A:"CDKN2A (p16), CDKN1A (p21), SASP 細胞因子", A_en:"CDKN2A (p16), CDKN1A (p21), SASP cytokines",
      B:"CASP3, BAX", B_en:"CASP3, BAX",
      C:"GPX4, ACSL4", C_en:"GPX4, ACSL4",
      D:"NLRP3, GSDMD", D_en:"NLRP3, GSDMD",
      ans:"A", exp:"老化不是死亡；要區分 apoptosis、ferroptosis、pyroptosis。", exp_en:"Senescence ≠ death; distinguish from apoptosis, ferroptosis, pyroptosis." },
    { type:"single", stem:"癌症最普遍突變的 tumor suppressor 是？", stem_en:"Most frequently mutated tumor suppressor in cancer?",
      A:"BRCA1", A_en:"BRCA1",
      B:"p53 (TP53)", B_en:"p53 (TP53)",
      C:"RB1", C_en:"RB1",
      D:"APC", D_en:"APC",
      ans:"B", exp:"&gt;50% 癌症 TP53 mut。", exp_en:">50% of cancers carry TP53 mutations." },
    { type:"single", stem:"Ferroptosis 的關鍵 marker？", stem_en:"Key ferroptosis marker?",
      A:"CASP3", A_en:"CASP3",
      B:"GPX4 下調、ACSL4 上調、lipid ROS", B_en:"GPX4 down, ACSL4 up, lipid ROS",
      C:"GSDMD", C_en:"GSDMD",
      D:"FOS / JUN", D_en:"FOS / JUN",
      ans:"B", exp:"Ferroptosis 為 iron-dependent lipid peroxidation。", exp_en:"Ferroptosis is iron-dependent lipid peroxidation." },
    { type:"multi", stem:"以下哪些是癌症常見訊號通路？（多選）", stem_en:"Common cancer signaling pathways? (Multi)",
      A:"RAS-MAPK", A_en:"RAS-MAPK",
      B:"PI3K-AKT-mTOR", B_en:"PI3K-AKT-mTOR",
      C:"WNT-β-catenin", C_en:"WNT-β-catenin",
      D:"光合作用", D_en:"Photosynthesis",
      ans:["A","B","C"], exp:"光合作用是植物代謝通路。", exp_en:"Photosynthesis is a plant metabolic pathway." },
    { type:"multi", stem:"哪些是 DNA 損傷檢查點關鍵激酶？（多選）", stem_en:"Key DDR checkpoint kinases? (Multi)",
      A:"ATM", A_en:"ATM",
      B:"ATR", B_en:"ATR",
      C:"CHK1 / CHK2", C_en:"CHK1 / CHK2",
      D:"AMPK", D_en:"AMPK",
      ans:["A","B","C"], exp:"AMPK 是能量訊號。", exp_en:"AMPK is an energy sensor." },
    { type:"tf", stem:"Rb 蛋白磷酸化後會釋放 E2F 並使細胞進入 S phase。", stem_en:"Rb phosphorylation releases E2F to drive S-phase entry.",
      ans:"T", exp:"CDK4/6 介導，被 CDK4/6 inhibitor（palbociclib）阻斷。", exp_en:"Mediated by CDK4/6; blocked by CDK4/6 inhibitors (palbociclib)." },
    { type:"tf", stem:"Pathway enrichment 在不同資料庫（Hallmark vs KEGG vs Reactome）結果可能不同。", stem_en:"Pathway enrichment results can differ across Hallmark vs KEGG vs Reactome databases.",
      ans:"T", exp:"資料庫範圍與 grouping 不同，應比對。", exp_en:"Scopes and groupings differ — cross-check." },
    { type:"single", stem:"BRCA1/2 與 PARP inhibitor 的關係是？", stem_en:"BRCA1/2 and PARP inhibitor relationship?",
      A:"BRCA mut → 抑制 PARP 有害", A_en:"BRCA mut + PARP inhibitor is harmful",
      B:"BRCA 缺陷 + PARP 抑制 → synthetic lethality（合成致死）", B_en:"BRCA-deficient + PARP inhibition = synthetic lethality",
      C:"PARP 與 BRCA 無關", C_en:"PARP and BRCA are unrelated",
      D:"BRCA mut 對 PARP 抑制有耐藥性", D_en:"BRCA mut confers PARPi resistance",
      ans:"B", exp:"olaparib / niraparib 等的核心機制。", exp_en:"Core mechanism of olaparib / niraparib." }
  ]
},

"Block D 組學與系統": {
  "Ch.14 定序技術與基因組學": [
    { type:"single", stem:"想偵測 200 bp tandem duplication，最易成功的方式？", stem_en:"To detect a 200 bp tandem duplication, the best path?",
      A:"Sanger 一個位點", A_en:"Sanger single locus",
      B:"Illumina short + 一般 SNV caller", B_en:"Illumina short + SNV caller",
      C:"long-read (PacBio HiFi / ONT) + SV caller", C_en:"long-read (PacBio HiFi / ONT) + SV caller",
      D:"WES + targeted panel", D_en:"WES + targeted panel",
      ans:"C", exp:"重複擴增 SV 是 long-read 的強項。", exp_en:"Repeat-rich SVs favor long-read." },
    { type:"single", stem:"臨床腫瘤偵測為什麼常用 targeted panel？", stem_en:"Why targeted panel for clinical oncology?",
      A:"panel 提供更長 read", A_en:"Panels yield longer reads",
      B:"高深度（500x+）能偵測低 VAF subclonal mutation、成本低、TAT 短", B_en:"Deep coverage (500×+) catches low-VAF subclonal mutations, cheap, fast TAT",
      C:"WGS 不能找 somatic 變異", C_en:"WGS can't find somatic",
      D:"WGS 報告太短", D_en:"WGS reports too short",
      ans:"B", exp:"低 VAF tumor mutation 需要 deep coverage。", exp_en:"Low-VAF tumor mutations need depth." },
    { type:"single", stem:"Reference bias 的最直接後果？", stem_en:"Most concrete consequence of reference bias?",
      A:"提高 Phred 品質", A_en:"Improves Phred quality",
      B:"加強非歐裔變異偵測", B_en:"Boosts non-European detection",
      C:"在非歐裔人群漏掉變異，加劇健康不平等", C_en:"Misses variants in non-Europeans, worsens health equity",
      D:"PCR duplicates 變少", D_en:"Reduces PCR duplicates",
      ans:"C", exp:"pangenome 與 graph 是解方。", exp_en:"Pangenome / graph genomes are the fix." },
    { type:"single", stem:"GATK HaplotypeCaller / DeepVariant 屬於哪一類 caller？", stem_en:"GATK HaplotypeCaller / DeepVariant are which type?",
      A:"germline SNV/indel caller", A_en:"germline SNV/indel caller",
      B:"somatic SV caller", B_en:"somatic SV caller",
      C:"RBP CLIP analyzer", C_en:"RBP CLIP analyzer",
      D:"圖譜基因組組裝器", D_en:"Graph genome assembler",
      ans:"A", exp:"germline 小變異主力工具。", exp_en:"Standard germline small-variant callers." },
    { type:"single", stem:"哪一技術是 long-read 高準確度的代表（Q30+）？", stem_en:"Which is the high-accuracy long-read tech (Q30+)?",
      A:"Sanger", A_en:"Sanger",
      B:"PacBio Revio HiFi", B_en:"PacBio Revio HiFi",
      C:"NovaSeq X", C_en:"NovaSeq X",
      D:"Element AVITI", D_en:"Element AVITI",
      ans:"B", exp:"HiFi 由多次 CCS 平均達到 Q30+。", exp_en:"HiFi achieves Q30+ via CCS consensus." },
    { type:"multi", stem:"以下哪些是 short-read aligner？（多選）", stem_en:"Which are short-read aligners? (Multi)",
      A:"BWA-MEM2", A_en:"BWA-MEM2",
      B:"Bowtie2", B_en:"Bowtie2",
      C:"STAR", C_en:"STAR",
      D:"minimap2", D_en:"minimap2",
      ans:["A","B","C"], exp:"minimap2 主要為 long-read。", exp_en:"minimap2 is mainly for long-read." },
    { type:"multi", stem:"哪些是 pangenome / graph genome 工具？（多選）", stem_en:"Which are pangenome / graph genome tools? (Multi)",
      A:"vg", A_en:"vg",
      B:"minigraph", B_en:"minigraph",
      C:"Giraffe", C_en:"Giraffe",
      D:"DESeq2", D_en:"DESeq2",
      ans:["A","B","C"], exp:"DESeq2 是 DE 工具。", exp_en:"DESeq2 is for DE." },
    { type:"tf", stem:"GATK Best Practices 涵蓋 germline / somatic / RNA-seq variant calling 全流程。", stem_en:"GATK Best Practices covers germline/somatic/RNA-seq calling.",
      ans:"T", exp:"是業界主要參考流程。", exp_en:"Industry-standard workflows." },
    { type:"tf", stem:"PCR duplicates 必須被標記或移除以避免變異 calling 偏差。", stem_en:"PCR duplicates should be marked/removed to avoid bias.",
      ans:"T", exp:"Picard MarkDuplicates / samtools markdup 是標準步驟。", exp_en:"Picard MarkDuplicates / samtools markdup are standard." },
    { type:"single", stem:"WES 大致覆蓋多少基因組比例？", stem_en:"WES covers approximately what fraction of the genome?",
      A:"~0.1%", A_en:"~0.1%",
      B:"~1%（約 30 Mb 編碼區）", B_en:"~1% (~30 Mb coding)",
      C:"~25%", C_en:"~25%",
      D:"~100%", D_en:"~100%",
      ans:"B", exp:"但藏 ~85% 致病變異。", exp_en:"Yet harbors ~85% disease variants." }
  ],
  "Ch.15 轉錄體學": [
    { type:"single", stem:"DE 分析最正確的輸入是？", stem_en:"Correct DE analysis input?",
      A:"TPM 後做 t-test", A_en:"TPM then t-test",
      B:"raw count 餵 DESeq2 / edgeR / limma-voom", B_en:"raw counts to DESeq2 / edgeR / limma-voom",
      C:"z-score 後 ANOVA", C_en:"z-score then ANOVA",
      D:"FPKM 後 ANOVA", D_en:"FPKM then ANOVA",
      ans:"B", exp:"工具基於 NB 模型，需 raw count。", exp_en:"Tools require raw counts for NB modeling." },
    { type:"single", stem:"scRNA-seq DE 為何推薦 pseudobulk？", stem_en:"Why pseudobulk for scRNA-seq DE?",
      A:"加快運算", A_en:"Faster",
      B:"細胞當 replicate 嚴重低估 sample variance → 假陽性；pseudobulk 修正", B_en:"Cell-level replicates underestimate sample variance → false positives; pseudobulk fixes",
      C:"提升 dropout", C_en:"Increases dropout",
      D:"適用 deep learning", D_en:"Better for DL",
      ans:"B", exp:"Squair 2021 系統評估。", exp_en:"Systematically assessed by Squair 2021." },
    { type:"single", stem:"Visium 與 Xenium 的根本差異？", stem_en:"Visium vs Xenium fundamental difference?",
      A:"完全相同", A_en:"Identical",
      B:"Visium = spot-based（多細胞）；Xenium = in-situ 次細胞、panel-based", B_en:"Visium = spot-based (multi-cell); Xenium = in-situ subcellular, panel-based",
      C:"Visium 偵測蛋白", C_en:"Visium detects protein",
      D:"Xenium 不能 FFPE", D_en:"Xenium can't FFPE",
      ans:"B", exp:"技術路線完全不同。", exp_en:"Different platforms." },
    { type:"single", stem:"TPM 比 FPKM 較適合跨樣本比較，原因？", stem_en:"Why TPM is more comparable across samples than FPKM?",
      A:"無理由", A_en:"No reason",
      B:"每樣本 TPM 加總固定為 10⁶，比例量化一致", B_en:"Per-sample TPM sums to 10⁶ — consistent across samples",
      C:"TPM 不考慮 length", C_en:"TPM ignores length",
      D:"TPM 是 raw count", D_en:"TPM is raw count",
      ans:"B", exp:"FPKM/RPKM 因順序不同無法保持加總相同。", exp_en:"FPKM/RPKM totals differ because of normalization order." },
    { type:"single", stem:"DESeq2 與 edgeR 共同基於哪一統計模型？", stem_en:"DESeq2 and edgeR share which statistical model?",
      A:"linear regression on TPM", A_en:"Linear regression on TPM",
      B:"negative binomial GLM", B_en:"Negative binomial GLM",
      C:"Poisson 全域", C_en:"Global Poisson",
      D:"Gaussian mixture", D_en:"Gaussian mixture",
      ans:"B", exp:"NB GLM 是 RNA-seq DE 標準假設。", exp_en:"NB GLM is the standard for RNA-seq DE." },
    { type:"multi", stem:"以下哪些是常見 scRNA-seq DE 工具/策略？（多選）", stem_en:"Common scRNA-seq DE strategies? (Multi)",
      A:"Wilcoxon / FindMarkers", A_en:"Wilcoxon / FindMarkers",
      B:"MAST", B_en:"MAST",
      C:"pseudobulk → DESeq2/edgeR", C_en:"pseudobulk → DESeq2/edgeR",
      D:"DiffBind", D_en:"DiffBind",
      ans:["A","B","C"], exp:"DiffBind 是 ChIP-seq DE。", exp_en:"DiffBind is for ChIP-seq DE." },
    { type:"multi", stem:"以下哪些屬於 spatial transcriptomics 技術？（多選）", stem_en:"Spatial transcriptomics platforms? (Multi)",
      A:"Visium", A_en:"Visium",
      B:"Xenium", B_en:"Xenium",
      C:"MERFISH", C_en:"MERFISH",
      D:"Sanger sequencing", D_en:"Sanger sequencing",
      ans:["A","B","C"], exp:"Sanger 不是 spatial。", exp_en:"Sanger isn't spatial." },
    { type:"tf", stem:"RNA-seq 是相對量化；全局 RNA 量改變會被標準化磨平，需 spike-in 校正。", stem_en:"RNA-seq is relative; global RNA shifts are masked by normalization — use spike-ins.",
      ans:"T", exp:"compositional bias 經典問題。", exp_en:"Compositional bias — classic issue." },
    { type:"tf", stem:"SCTransform 改用 NB regression 殘差，減少 sequencing depth 的影響。", stem_en:"SCTransform uses NB-regression residuals to remove depth bias.",
      ans:"T", exp:"Hafemeister & Satija 2019 提出。", exp_en:"Hafemeister & Satija 2019." },
    { type:"single", stem:"Long-read RNA-seq（PacBio Iso-Seq、ONT direct）的主要優勢？", stem_en:"Main advantage of long-read RNA-seq (Iso-Seq, ONT direct)?",
      A:"低成本", A_en:"Low cost",
      B:"高通量", B_en:"High throughput",
      C:"全長 isoform 解析、native modification", C_en:"Full-length isoform resolution, native modifications",
      D:"短讀更便宜", D_en:"Cheaper short reads",
      ans:"C", exp:"isoform 與 modification 是 long-read 的強項。", exp_en:"Isoforms and modifications are long-read strengths." }
  ],
  "Ch.16 蛋白質體與翻譯後修飾": [
    { type:"single", stem:"想做大規模、跨樣本可重現的蛋白質定量，最合適採集模式？", stem_en:"Best acquisition for large-scale reproducible quantitation?",
      A:"DDA top-3", A_en:"DDA top-3",
      B:"DIA（廣覆蓋、高重現性、少 missing value）", B_en:"DIA (broad coverage, reproducible, few missing values)",
      C:"抗體陣列", C_en:"Antibody array",
      D:"只跑單樣本", D_en:"Single sample only",
      ans:"B", exp:"DIA 適合大樣本 cohort。", exp_en:"DIA suits large cohorts." },
    { type:"single", stem:"磷酸化富集最常用方法？", stem_en:"Most common phospho-enrichment?",
      A:"抗體 IP", A_en:"Antibody IP",
      B:"PNGase F 處理", B_en:"PNGase F treatment",
      C:"TiO₂ 或 IMAC", C_en:"TiO₂ or IMAC",
      D:"Lectin 親和", D_en:"Lectin affinity",
      ans:"C", exp:"金屬親和富集標準。", exp_en:"Metal-affinity enrichment standard." },
    { type:"single", stem:"TMT 多通道實驗最被批評的偏差？", stem_en:"Most criticized TMT multiplex bias?",
      A:"完全沒 missing value", A_en:"No missing values",
      B:"Ratio compression（共流出胜肽干擾比值）", B_en:"Ratio compression (co-eluting peptides flatten ratios)",
      C:"必要新鮮冷凍", C_en:"Requires fresh-frozen",
      D:"無法 DIA 結合", D_en:"Cannot combine with DIA",
      ans:"B", exp:"co-elution 干擾 reporter ion 強度。", exp_en:"Co-elution distorts reporter ion intensity." },
    { type:"single", stem:"bottom-up 質譜中常用 protease 是？", stem_en:"Common protease in bottom-up MS?",
      A:"DNase", A_en:"DNase",
      B:"Trypsin（切 K/R 之後）", B_en:"Trypsin (after K/R)",
      C:"RNase", C_en:"RNase",
      D:"Polymerase", D_en:"Polymerase",
      ans:"B", exp:"Trypsin 是金標準。", exp_en:"Trypsin is the gold standard." },
    { type:"single", stem:"PTM 「GG remnant」抗體用於富集？", stem_en:"Anti-GG remnant antibody enriches?",
      A:"Phospho", A_en:"Phospho",
      B:"Acetyl", B_en:"Acetyl",
      C:"Ubiquitination（trypsin 切後 ubiquitin 殘留 GG）", C_en:"Ubiquitination (GG left after trypsin)",
      D:"O-GlcNAc", D_en:"O-GlcNAc",
      ans:"C", exp:"K-GG site 為 ubiquitin K-link 證據。", exp_en:"K-GG marks the ubiquitin K-linkage." },
    { type:"multi", stem:"以下哪些是 DIA 分析工具？（多選）", stem_en:"DIA analysis tools? (Multi)",
      A:"Spectronaut", A_en:"Spectronaut",
      B:"DIA-NN", B_en:"DIA-NN",
      C:"Skyline", C_en:"Skyline",
      D:"MAGeCK", D_en:"MAGeCK",
      ans:["A","B","C"], exp:"MAGeCK 是 CRISPR screen 分析。", exp_en:"MAGeCK is for CRISPR screens." },
    { type:"multi", stem:"以下哪些是常見 PTM？（多選）", stem_en:"Common PTMs? (Multi)",
      A:"phosphorylation", A_en:"phosphorylation",
      B:"acetylation", B_en:"acetylation",
      C:"ubiquitination", C_en:"ubiquitination",
      D:"alternative splicing", D_en:"alternative splicing",
      ans:["A","B","C"], exp:"alternative splicing 是 RNA 層級。", exp_en:"Alternative splicing is at the RNA level." },
    { type:"tf", stem:"頂底 top-down 蛋白體適合分析完整 proteoforms 與 PTM 組合。", stem_en:"Top-down proteomics suits intact proteoforms and PTM combinations.",
      ans:"T", exp:"但通量低、需高解析儀器。", exp_en:"But low throughput; high-res instruments needed." },
    { type:"tf", stem:"label-free quantification (LFQ) 沒有 missing value 問題。", stem_en:"LFQ has no missing-value problem.",
      ans:"F", exp:"LFQ 仍受 ion suppression 與 DDA 隨機選樣影響。", exp_en:"LFQ still suffers from ion suppression and DDA stochasticity." },
    { type:"single", stem:"FDR 控制在 proteomics 中至少要在哪幾個層級進行？", stem_en:"Proteomics FDR should be controlled at which levels?",
      A:"只在 PSM", A_en:"PSM only",
      B:"PSM / peptide / protein 三層", B_en:"PSM / peptide / protein triple",
      C:"只在 protein", C_en:"protein only",
      D:"不用 FDR", D_en:"No FDR needed",
      ans:"B", exp:"三層 FDR 為現代 proteomics 標準。", exp_en:"Triple-level FDR is the modern standard." }
  ],
  "Ch.17 代謝體與脂質體": [
    { type:"single", stem:"報告「找到 metabolite X」未說 MSI level，問題在？", stem_en:"Reporting 'found X' without MSI level is problematic because?",
      A:"完全可信", A_en:"Fully trustworthy",
      B:"可能僅 L2/L3 註解，同分異構物混淆", B_en:"May only be L2/L3 — confounded by isomers",
      C:"必為 L1", C_en:"Must be L1",
      D:"與技術無關", D_en:"Irrelevant",
      ans:"B", exp:"應公開 MSI level。", exp_en:"Disclose MSI level." },
    { type:"single", stem:"極性代謝物（aa、有機酸）常用 LC 管柱？", stem_en:"LC column for polar metabolites (aa, organic acids)?",
      A:"C18 reverse-phase", A_en:"C18 reverse-phase",
      B:"SCX", B_en:"SCX",
      C:"HILIC", C_en:"HILIC",
      D:"SEC", D_en:"SEC",
      ans:"C", exp:"親水交互作用色譜。", exp_en:"Hydrophilic interaction chromatography." },
    { type:"single", stem:"血液取樣後處理時間對代謝體為何特別關鍵？", stem_en:"Why is handling time critical for metabolomics?",
      A:"無影響", A_en:"No effect",
      B:"紅血球繼續代謝、酵素持續活動，代謝物變化以秒計", B_en:"RBCs keep metabolizing; metabolites shift in seconds",
      C:"處理越久越準", C_en:"Longer is better",
      D:"只影響 RNA-seq", D_en:"Only RNA-seq",
      ans:"B", exp:"pre-analytical 變異是最大誤差來源。", exp_en:"Pre-analytical variance is the biggest source." },
    { type:"single", stem:"以下哪一個是脂質類別資料庫？", stem_en:"Which is a lipid class database?",
      A:"HMDB", A_en:"HMDB",
      B:"LIPID MAPS", B_en:"LIPID MAPS",
      C:"ClinVar", C_en:"ClinVar",
      D:"PhosphoSitePlus", D_en:"PhosphoSitePlus",
      ans:"B", exp:"LIPID MAPS 提供結構與命名標準。", exp_en:"LIPID MAPS provides structures and naming." },
    { type:"single", stem:"Lipidomics 解析需要區分幾個層次？", stem_en:"Lipidomics annotation requires how many levels?",
      A:"只有單一層", A_en:"Single level",
      B:"class / subclass / acyl chain 三層", B_en:"class / subclass / acyl chain (three)",
      C:"五層", C_en:"five",
      D:"與蛋白同層", D_en:"Same as protein",
      ans:"B", exp:"由 LIPID MAPS 規範。", exp_en:"As specified by LIPID MAPS." },
    { type:"multi", stem:"哪些屬於代謝體分析工具？（多選）", stem_en:"Metabolomics tools? (Multi)",
      A:"XCMS", A_en:"XCMS",
      B:"MZmine", B_en:"MZmine",
      C:"MetaboAnalyst", C_en:"MetaboAnalyst",
      D:"Seurat", D_en:"Seurat",
      ans:["A","B","C"], exp:"Seurat 是 scRNA-seq。", exp_en:"Seurat is for scRNA-seq." },
    { type:"multi", stem:"以下哪些是脂質體分析工具？（多選）", stem_en:"Lipidomics annotation tools? (Multi)",
      A:"LipidSearch", A_en:"LipidSearch",
      B:"LipidBlast", B_en:"LipidBlast",
      C:"MS-DIAL", C_en:"MS-DIAL",
      D:"Bowtie2", D_en:"Bowtie2",
      ans:["A","B","C"], exp:"Bowtie2 是定序比對工具。", exp_en:"Bowtie2 is a sequence aligner." },
    { type:"tf", stem:"NMR 在代謝體中可提供絕對定量，但敏感度比 MS 低數量級。", stem_en:"NMR provides absolute quantitation in metabolomics but is orders of magnitude less sensitive than MS.",
      ans:"T", exp:"NMR 適合體液大規模研究。", exp_en:"NMR is suitable for large biofluid studies." },
    { type:"tf", stem:"Lipidome 約 40K 結構（不含同分異構），需 panel/MS² 才能解析。", stem_en:"~40K lipid structures (excluding isomers); MS² needed to resolve.",
      ans:"T", exp:"isomer 問題使解析困難。", exp_en:"Isomers complicate annotation." },
    { type:"single", stem:"代謝體 untargeted 與 targeted 分析最大區別？", stem_en:"Biggest difference between untargeted and targeted metabolomics?",
      A:"無區別", A_en:"None",
      B:"untargeted 廣覆蓋掃描，先發現再驗證；targeted 預先指定一組已知代謝物精確定量", B_en:"Untargeted scans broadly to discover; targeted measures a pre-specified panel with absolute quantitation",
      C:"untargeted 一定更準", C_en:"Untargeted is always more accurate",
      D:"targeted 不需標準品", D_en:"Targeted needs no standards",
      ans:"B", exp:"兩者目的不同；常先 untargeted 後 targeted 驗證。", exp_en:"Different goals — often untargeted discovery → targeted validation." }
  ],
  "Ch.18 系統生物學、多組學與臨床": [
    { type:"single", stem:"MOFA+ / totalVI / scGLUE 屬於？", stem_en:"MOFA+ / totalVI / scGLUE belong to?",
      A:"早期整合（concat）", A_en:"Early (concat)",
      B:"中期整合（latent alignment / shared factors）", B_en:"Intermediate (latent alignment / shared factors)",
      C:"晚期整合（meta-analysis）", C_en:"Late (meta-analysis)",
      D:"完全無整合", D_en:"None",
      ans:"B", exp:"latent-level 整合是當前主流。", exp_en:"Latent-level integration is current best practice." },
    { type:"single", stem:"FAIR 原則指？", stem_en:"FAIR principles?",
      A:"Fast / Accurate / Inexpensive / Reproducible", A_en:"Fast / Accurate / Inexpensive / Reproducible",
      B:"Federated / Anonymous / Inferred / Random", B_en:"Federated / Anonymous / Inferred / Random",
      C:"Findable / Accessible / Interoperable / Reusable", C_en:"Findable / Accessible / Interoperable / Reusable",
      D:"Functional / Annotated / Indexed / Reviewed", D_en:"Functional / Annotated / Indexed / Reviewed",
      ans:"C", exp:"Wilkinson 2016 提出。", exp_en:"Wilkinson 2016." },
    { type:"single", stem:"ACMG SF v3.2 次要發現的核心精神？", stem_en:"Core spirit of ACMG SF v3.2 secondary findings?",
      A:"禁止告知任何意外發現", A_en:"Prohibit disclosing any incidental findings",
      B:"所有變異都須報告", B_en:"All variants must be reported",
      C:"特定 actionable 基因主動回報，可 opt-out", C_en:"Specific actionable genes proactively returned, patient opt-out",
      D:"全面禁止 germline editing", D_en:"Ban germline editing",
      ans:"C", exp:"81 actionable genes 為 v3.2 列表。", exp_en:"v3.2 lists 81 actionable genes." },
    { type:"single", stem:"FBA（flux balance analysis）主要用於？", stem_en:"FBA mainly used for?",
      A:"變異註解", A_en:"Variant annotation",
      B:"代謝網絡通量分析、metabolic engineering", B_en:"Metabolic flux analysis and engineering",
      C:"protein structure", C_en:"Protein structure",
      D:"sequence alignment", D_en:"Sequence alignment",
      ans:"B", exp:"FBA 計算穩態流量分配。", exp_en:"FBA computes steady-state flux distribution." },
    { type:"single", stem:"CPIC 指南屬於？", stem_en:"CPIC guidelines are?",
      A:"癌症定序 panel", A_en:"Cancer sequencing panel",
      B:"基因組分析方法 benchmark", B_en:"Methods benchmark",
      C:"藥物基因組學處方建議（CYP2D6, TPMT, ...）", C_en:"Pharmacogenomic prescribing recommendations (CYP2D6, TPMT, ...)",
      D:"資料分享原則", D_en:"Data sharing policy",
      ans:"C", exp:"clinically actionable PGx guidance。", exp_en:"Clinically actionable PGx guidance." },
    { type:"multi", stem:"哪些是臨床精準醫療的關鍵生物資訊輸出？（多選）", stem_en:"Key bioinformatics outputs for precision medicine? (Multi)",
      A:"variant calls + ACMG 致病性", A_en:"variant calls + ACMG pathogenicity",
      B:"TMB / MSI / HRD score", B_en:"TMB / MSI / HRD score",
      C:"HLA typing + neoantigen prediction", C_en:"HLA typing + neoantigen prediction",
      D:"galaxy image", D_en:"Galaxy image",
      ans:["A","B","C"], exp:"galaxy 是天文物件，不在臨床。", exp_en:"Galaxy image isn't a clinical readout." },
    { type:"multi", stem:"哪些是多組學整合策略？（多選）", stem_en:"Which are multi-omics integration strategies? (Multi)",
      A:"早期（early）", A_en:"Early",
      B:"中期（intermediate）", B_en:"Intermediate",
      C:"晚期（late / meta）", C_en:"Late / meta",
      D:"PCR 純化", D_en:"PCR purification",
      ans:["A","B","C"], exp:"PCR 純化是實驗步驟。", exp_en:"PCR purification is a wet-lab step." },
    { type:"tf", stem:"PRS 在多數族群仍有公平性問題；以歐裔權重套用非歐裔會降低預測力。", stem_en:"PRS faces equity issues across ancestries; European-trained PRS reduces accuracy in non-Europeans.",
      ans:"T", exp:"Martin 2019 等多篇研究確認。", exp_en:"Confirmed by Martin 2019 et al." },
    { type:"tf", stem:"基因組資料一旦發布即可被有效『匿名遺忘』。", stem_en:"Genomic data, once released, can be effectively 'forgotten'.",
      ans:"F", exp:"基因組高度識別性，無法真正撤回。", exp_en:"Genomes are uniquely identifying; full retraction is impossible." },
    { type:"single", stem:"在臨床定序中，「return of secondary findings」的核心要件？", stem_en:"For 'return of secondary findings' in clinical sequencing, the core requirement?",
      A:"自由選擇全部回報", A_en:"Always return all findings",
      B:"病人事先知情同意、可選擇 opt-in / opt-out", B_en:"Informed consent in advance with opt-in / opt-out",
      C:"必須由保險公司決定", C_en:"Decided by insurance",
      D:"無需告知病人", D_en:"No need to inform patient",
      ans:"B", exp:"ACMG SF v3.2 強調知情同意。", exp_en:"ACMG SF v3.2 emphasizes informed consent." }
  ]
}

    }
  }
};
